# Generated by Django 3.0.7 on 2021-02-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
    ]
